
[project]
name = "CritBot"
version = "0.1.0"
description = "A really cool Discord Bot"
authors = [
    {name = "Lucas de Linhares", email = "lucasdelinhares@gmail.com"},
]
dependencies = [
    "aiofiles==23.1.0",
    "aiohttp>=3.8.4",
    "asyncpg==0.27.0",
    "colorlog==6.7.0",
    "discord-py[speed]==2.2.3",
    "discord-py[voice]==2.2.3",
    "PyYAML==6.0",
    "uvloop==0.17.0",
    "wavelink==1.3.5",
    "psutil==5.9.5",
    "yt-dlp==2023.3.4",
    "lru-dict==1.1.8",
    "lxml==4.9.2",
    "asyncpraw==7.7.0",
]
requires-python = ">=3.10"
license = {text = "GPL-3.0"}
homepage = "https://github.com/lucascompython/critbot"
repository = {type = "git", url = "https://github.com/lucascompython/critbot.git"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "ruff>=0.0.275",
    "mypy>=1.4.1",
]

[tool.pdm.resolution.overrides]
aiofiles = "23.1.0"

[tool.pdm.scripts]
lint = "ruff lint ."
types = "mypy . --explicit-package-bases"
all = {composite = ["lint", "types"]}
start = "python3 launcher.py {args}" # yes, I could use call but then I would have to rewrite the args part
setup = "./setup.sh"
